name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
  - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
          
          -name: Login to DockeHub
           user: docker/login-action@v1
           with: 
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      run: go build and push -v ./...

    - name: Test and push
      run: go test and push -v ./...

  
